### PR TITLE
Merge linear streams2

### LINKED ISSUE #162: Merge linear-streams and migrate issues
Merge (via git-subtree-ing) an optimized, documented version of linear-streams (with sufficient workarounds for the API that can't be implemented properly without affine streams, e.g., `readStdinUntil :: (String -> Bool) -> Stream (Of String) IO ()`).

### PR DESCRIPTION
**Pull request by Divesh-Otwani**
Replacing #202 because I want to clean up the commits. I made all requested changes from the discussion in #202. 

# Copied description 

This PR moves linear-streams into linear-base. A migration of the issues with a tag will follow the merge.
All the changes in linear-streams have already been reviewed so this PR is about just checking if the merge is clean.
The linear-streams repository will be deleted following the merge.

Depends on #200 and depends on #201.
Finally closes #162.

### CODE REVIEW

**Review by utdemir — APPROVED** [review]
If the code is already reviewed, there is not much for me to do; this looks good to me.

**Comment by aspiwack** [comment]
>  The linear-streams repository will be deleted following the merge.

This was a bad idea. We lost all the corresponding PR discussion and such. It's better to just archive the repository.

**Comment by Divesh-Otwani** [comment]
Yes, I don't know how I missed that we'd lose the PR discussions. _Will **not** do this doing forward._

**Comment by aspiwack** [comment]
Well, it turns out that you can undelete repository for a short while. So I did, and archived it: https://github.com/tweag/linear-streams/ .

**Comment by Divesh-Otwani** [comment]
Whoo!

**Pull request merged**
