### PR TITLE
fix: deprecated '-->.' notation

### PR DESCRIPTION
**Pull request by nbacquey**
Use 'FUN' from GHC.Exts
Instead of 'a -->.(p) b' we now have 'FUN p a b'

### CODE REVIEW

**Comment by monoidal** [comment]
CI uses an older version of linear types, which does not export FUN yet.

**Comment by facundominguez** [comment]
I don't have a clue of how to fix the current CI failure. Probably we should try GHC head and see if it occurs with it, before investigating further.

**Comment by facundominguez** [comment]
I'm trying with GHC HEAD now.

**Comment by Divesh-Otwani** [comment]
Hey, @facundominguez  just wanted to say thank you for this and the update to GHC HEAD!

**Comment by facundominguez** [comment]
Kudos to @nbacquey for starting the PR.

**Comment by Divesh-Otwani** [comment]
Thanks @nbacquey :)

**Pull request merged**
